// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUzjs0bkUhD4e7P5v0sMuMjwYKlwI7OjM',
    appId: '1:207042530450:web:8190945a3a84cd945caa4b',
    messagingSenderId: '207042530450',
    projectId: 'preschoolapp-9c124',
    authDomain: 'preschoolapp-9c124.firebaseapp.com',
    storageBucket: 'preschoolapp-9c124.appspot.com',
    measurementId: 'G-MBCRHGHJR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAju_TRfSpPwbTNPHnAK_V4NaMQMeNXZnU',
    appId: '1:207042530450:android:781bc03db109e6d85caa4b',
    messagingSenderId: '207042530450',
    projectId: 'preschoolapp-9c124',
    storageBucket: 'preschoolapp-9c124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTvvRsRP0q0Y6odWJoK9y1fKmv1JxNB4k',
    appId: '1:207042530450:ios:f76b0407b32c64b05caa4b',
    messagingSenderId: '207042530450',
    projectId: 'preschoolapp-9c124',
    storageBucket: 'preschoolapp-9c124.appspot.com',
    iosBundleId: 'com.example.projectV1',
  );
}
